config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resources :players do
      resources :frames
    end
    resources :frames
  end

  resources :frames do
    resources :players do
      resources :balls
    end
    resources :balls
  end

  resources :balls

  root 'games#index'

end

app/models/ball.rb
class Ball < ActiveRecord::Base
  belongs_to :frame
  belongs_to :player

  def first_ball
    pins_kncked = rand(0..10)
  end

  def second_ball(pins_knocked1)
    remaining_pins = 10 - pins_knocked1
    pins_kncked = rand(0.. remaining_pins)
  end

  def strike?
    self.first_ball == 10
  end

  def spare?
    self.first_ball + self.second_ball == 10
  end

  def score_update
    player  = self.player_id
    game    = self.frame.game_id
    points  = self.pins_knocked1 + self.pins_knocked2 unless self.pins_knocked2.nil?

    score = Score.create_with(total: points).find_or_create_by(player_id: player, game_id: game)
  end
end

app/models/frame.rb
class Frame < ActiveRecord::Base
  belongs_to :game
  has_many :balls

  def strike?
    self.balls.first.pins_koncked1 == 10
  end

  def spare?
    self.balls.pins.pins_koncke1 + self.balls.pins_koncked2 == 10
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :players
  has_many :frames
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game

  def running_score
    normal_score = Ball.where('player_id = ? AND pins_knocked2 IS NOT NULL', self.id).sum("pins_knocked1") +
                   Ball.where('player_id = ? AND pins_knocked2 IS NOT NULL', self.id).sum("pins_knocked2")
  end
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :game
  belongs_to :player
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/balls_controller.rb
class BallsController < ApplicationController

  before_action :set_frame, except: [:show]

  def new
    @ball = @frame.balls.build
  end

  def create
    @ball = @frame.balls.build(ball_params)
    @game_players = @ball.frame.game.players.to_a
    @game_players_no = @game_players.count

    @current_player_id = params[:ball][:player_id]

    if @frame.balls.where('player_id = ?', @current_player_id).count == 0
      @ball.pins_knocked1 = @ball.first_ball
      @ball.player_id = @current_player_id
    elsif @frame.balls.where('player_id = ?', @current_player_id).count == 1
      @ball.pins_knocked1 = @frame.balls.where('player_id = ?', @current_player_id).first.pins_knocked1
      @ball.pins_knocked2 = @ball.second_ball(@frame.balls.where('player_id = ?', @current_player_id).first.pins_knocked1)
      @ball.player_id = @current_player_id
    end

    if @ball.save
      @ball.score_update
      #if @frame.where('game_id = ?', @frame.game).count == 10
      #  flash['End of Game']
      #  redirect_to root_path
      #else
        if @frame.balls.count == @game_players_no * 2
          redirect_to new_game_frame_path(@frame.game)
        else
          redirect_to frame_balls_path
        end
      #end
    else
      show 'new'
    end
  end

  def index
    @balls = Ball.where('frame_id = ?', params[:frame_id])
    @ball = @frame.balls.build
    @game = @frame.game
    @game_players = @frame.game.players
    @players_score = Score.where(game_id: @game.id)
  end

  private

  def set_frame
    @frame = Frame.find(params[:frame_id])
  end

  def ball_params
    params.require(:ball).permit(:player_id) || nil
  end

end

app/controllers/frames_controller.rb
class FramesController < ApplicationController

  before_action :set_game, except: [:index, :show]

  def new
    @frame = @game.frames.build
  end

  def create
    # return if frames are > 10 not strike/spare in the last one
    @frame = @game.frames.build
    if @frame.save
      flash[:notice] = "Frame has been created."
      redirect_to @frame
    else
      flash[:alert] = "Frame has not been created."
      render "new"
    end
  end

  def show
    @frame = Frame.find(params[:id])
  end

  private

  def set_game
    @game = Game.find(params[:game_id])
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      flash[:notice] = 'Game has been created.'
      redirect_to @game, notice: 'Game has been created.'
    else
      flash[:alert] = 'Game has not been created.'
      render 'new'
    end
  end

  def show
    @game = Game.find(params[:id])
  end

  private

  def game_params
    params.require(:game).permit(:players_no)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_action :set_game

  def new
    @player = @game.players.build
  end

  def create
    @player = @game.players.build(player_params)
    if @player.save
      flash[:notice] = "Player has been created."
      redirect_to @game
    else
      flash[:alert] = "Player has not been created."
      render "new"
    end
  end

  private
    def set_game
      @game = Game.find(params[:game_id])
    end

    def player_params
      params.require(:player).permit(:first_name, :surname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/balls/_score.html.erb
<h2>Running Score</h2>

<ul>
  <% @players_score.each do |score| %>
    <li><%= score.player.first_name %> <%= score.total %></li>
  <% end %>
</ul>

app/views/balls/index.html.erb
<h2>Drop some pins</h2>

<ul>
  <% @balls.each do |ball| %>
    <% ball.frame.game.players.each do |player| %>
      <% if player.id == ball.player_id %>
        <li><%= player.first_name %>
            Ball1 : <%= ball.pins_knocked1 %>
            Ball2 : <%= ball.pins_knocked2 %>
        </li>
      <% end %>
    <% end %>
  <% end %>
</ul>

<%= form_for [@frame, @ball]  do |f| %>
  <div>
    <%= f.label :player_id %><br>
    <%= f.select(:player_id, options_from_collection_for_select(@ball.frame.game.players, :id, :first_name), {prompt: 'Please Choose'} ) %>
  </div>
  <%= f.submit %>
<% end %>

<div>
  <%= render "score" %>
</div>

app/views/balls/new.html.erb
<h2>Roll the ball</h2>

<%= form_for [@frame, @ball] do |f| %>
  <%= f.hidden_field(:player_id, value: @ball.frame.game.players.first.id ) %>
  <%= f.submit %>
<% end %>

app/views/frames/new.html.erb
<h2>New Frame</h2>

<%= form_for [@game, @frame] do |f| %>
  <%= f.submit %>
<% end %>

app/views/frames/show.html.erb
<h2>Frame</h2>

Current frame is : <%= @frame.id %>
<p>
  <%= link_to 'Roll ball', new_frame_ball_path(@frame) %>
</p>

app/views/games/index.html.erb
<div><%= link_to 'Start New Game', new_game_path %> </div>

<h2>Games</h2>
<ul>
  <% @games.each do |game| %>
    <li><%= link_to game.id, game %></li>
  <% end %>
</ul>

app/views/games/new.html.erb
<div>Press the button below to start new game</dv>

<%= form_for(@game) do |f| %>

  <p>
    <%= f.label :players_no, 'Enter number of players' %>
    <%= f.number_field :players_no %>
  </p>

  <%= f.submit %>
<% end %>

app/views/games/show.html.erb
<h2>Game No : <%= @game.id %></h2>
<div>Number of players : <%= @game.players_no %></div>

<div>
  <ul>
    <% @game.players.each do |player| %>
      <li><%= player.first_name %> <%= player.surname %></li>
    <% end %>
  </ul>
</div>

<% if @game.players.count < @game.players_no %>
  <div><%= link_to 'Add player', new_game_player_path(@game) %>
<% else %>
  <div><%= link_to 'Start Game', new_game_frame_path(@game) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tpb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class="flash" id="<%= key %>">
    <%= value %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/players/new.html.erb
<h2>New Player</h2>

<%= form_for [@game, @player] do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prevented this player from being saved.</h2>

      <ul>
        <% @player.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </p>
  <%= f.submit %>
<% end %>